IVERILOG = iverilog -DSIMULATION
VVP = vvp
COCOTB_PREFIX = $(shell cocotb-config --prefix)

COCOTB_LIBS = $(COCOTB_PREFIX)/cocotb/libs

SIM_BUILD_DIR = sim_build/pipeline_exp
SIM_VVP = $(SIM_BUILD_DIR)/tpu_pipeline.vvp

export COCOTB_REDUCED_LOG_FMT=1
export LIBPYTHON_LOC=$(shell cocotb-config --libpython)
export PYTHONPATH := test:$(PYTHONPATH)

PIPELINE_SOURCES = src/pe.sv \
                   src/leaky_relu_child.sv \
                   src/leaky_relu_parent.sv \
                   src/leaky_relu_derivative_child.sv \
                   src/leaky_relu_derivative_parent.sv \
                   src/systolic.sv \
                   src/bias_child.sv \
                   src/bias_parent.sv \
                   src/fixedpoint.sv \
                   src/control_unit.sv \
                   src/unified_buffer_v3.sv \
                   src/vpu.sv \
                   src/loss_parent.sv \
                   src/loss_child.sv \
                   src/gradient_descent.sv \
                   src/pipeline_exp/vpu_ub_pipe_stage.sv \
                   src/pipeline_exp/tpu_pipeline.sv

$(SIM_BUILD_DIR):
	mkdir -p $(SIM_BUILD_DIR)
	mkdir -p waveforms

test_tpu_pipeline_verify: $(SIM_BUILD_DIR)
	$(IVERILOG) -o $(SIM_VVP) -s tpu_pipeline -s dump -g2012 $(PIPELINE_SOURCES) test/dump_tpu_pipeline.sv
	PYTHONOPTIMIZE=$(NOASSERT) MODULE=test_tpu_verification $(VVP) -M $(COCOTB_LIBS) -m libcocotbvpi_icarus $(SIM_VVP)
	! grep failure results.xml

test_tpu_pipeline: $(SIM_BUILD_DIR)
	$(IVERILOG) -o $(SIM_VVP) -s tpu_pipeline -s dump -g2012 $(PIPELINE_SOURCES) test/dump_tpu_pipeline.sv
	PYTHONOPTIMIZE=$(NOASSERT) MODULE=test_tpu $(VVP) -M $(COCOTB_LIBS) -m libcocotbvpi_icarus $(SIM_VVP)
	! grep failure results.xml

clean_pipeline:
	rm -rf waveforms/tpu_pipeline.vcd $(SIM_BUILD_DIR) results.xml

.PHONY: test_tpu_pipeline_verify test_tpu_pipeline clean_pipeline
