IVERILOG = iverilog -DSIMULATION
VVP = vvp
COCOTB_PREFIX = $(shell cocotb-config --prefix)

COCOTB_LIBS = $(COCOTB_PREFIX)/cocotb/libs

SIM_BUILD_DIR = sim_build/handshake_exp
SKID_VVP = $(SIM_BUILD_DIR)/vpu_ub_skid_stage.vvp
TPU_HANDSHAKE_VVP = $(SIM_BUILD_DIR)/tpu_handshake.vvp

export COCOTB_REDUCED_LOG_FMT=1
export LIBPYTHON_LOC=$(shell cocotb-config --libpython)
export PYTHONPATH := test:$(PYTHONPATH)

SKID_SOURCES = src/handshake_exp/vpu_ub_skid_stage.sv

TPU_HANDSHAKE_SOURCES = src/pe.sv \
                        src/leaky_relu_child.sv \
                        src/leaky_relu_parent.sv \
                        src/leaky_relu_derivative_child.sv \
                        src/leaky_relu_derivative_parent.sv \
                        src/systolic.sv \
                        src/bias_child.sv \
                        src/bias_parent.sv \
                        src/fixedpoint.sv \
                        src/control_unit.sv \
                        src/unified_buffer_v3.sv \
                        src/vpu.sv \
                        src/loss_parent.sv \
                        src/loss_child.sv \
                        src/gradient_descent.sv \
                        src/handshake_exp/vpu_ub_skid_stage.sv \
                        src/handshake_exp/tpu_handshake.sv

$(SIM_BUILD_DIR):
	mkdir -p $(SIM_BUILD_DIR)
	mkdir -p waveforms

test_vpu_ub_skid_stage_verify: $(SIM_BUILD_DIR)
	$(IVERILOG) -o $(SKID_VVP) -s vpu_ub_skid_stage -s dump -g2012 $(SKID_SOURCES) test/dump_vpu_ub_skid_stage.sv
	PYTHONOPTIMIZE=$(NOASSERT) MODULE=test_vpu_ub_skid_stage $(VVP) -M $(COCOTB_LIBS) -m libcocotbvpi_icarus $(SKID_VVP)
	! grep failure results.xml

compile_tpu_handshake: $(SIM_BUILD_DIR)
	$(IVERILOG) -o $(TPU_HANDSHAKE_VVP) -s tpu_handshake -s dump -g2012 $(TPU_HANDSHAKE_SOURCES) test/dump_tpu_handshake.sv

clean_handshake:
	rm -rf waveforms/vpu_ub_skid_stage.vcd waveforms/tpu_handshake.vcd $(SIM_BUILD_DIR) results.xml

.PHONY: test_vpu_ub_skid_stage_verify compile_tpu_handshake clean_handshake
